### ISSUE TITLE
Node modules folder

### ISSUE THREAD

**Issue by BrainMaestro** [Rawnly/tmdb-cli#1]
Hey! This is a really cool project. I've wanted to do this for a while. 

However, I noticed that you committed your `node_modules` folder. Is there a specific reason for this? It's usually included in the .gitignore file. Look at [this](https://byjoeybaker.com/why-you-should-never-commit-node-modules-in-nodejs).

**Comment by rawnly** [comment]
Oh thanks! I forgot the gitignore/npignore file!!
